# Generated by Django 4.2.4 on 2023-09-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=100)),
                ('destination_location', models.CharField(max_length=100)),
                ('start_department', models.CharField(max_length=100)),
                ('destination_department', models.CharField(max_length=100)),
                ('name_of_item', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('purpose_of_movement', models.TextField()),
                ('approval_person_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='topic',
        ),
        migrations.DeleteModel(
            name='AccessRecord',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Webpage',
        ),
    ]
