# Generated by Django 4.2.4 on 2023-09-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec_app', '0003_userprofileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='Level_one_approval',
            field=models.CharField(choices=[('rachu01gautam02@gmail.com', 'Rachana Pandey'), ('dcegmhx@gmail.com', 'Ashok Kumar Pandey')], default='rachu01gautam02@gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='movement',
            name='Level_two_approval',
            field=models.CharField(choices=[('rachu01gautam02@gmail.com', 'Rachana Pandey'), ('dcegmhx@gmail.com', 'Ashok Kumar Pandey')], default='rachu01gautam02@gmail.com', max_length=50),
        ),
    ]
